
<field:authors itemname="主演" autofield="1" notsend="0" type="multitext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:authors>
<field:areas itemname="地区" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="60" page="">
</field:areas>
<field:murls itemname="下载地址" autofield="1" notsend="0" type="multitext" isnull="true" islist="0" default=""  maxlength="250" page="">
</field:murls>
<field:body itemname="文章内容" autofield="0" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="" page="split">	
</field:body>	
