<?php
$z[0]=Array("specnote","\r\n                <li><a href=\"[field:arcurl /]\" target=\"_blank\">[field:title /]</a><span class=\"date\">[field:typename/]</span></li>\r\n                ",0,385);
$z[0][4]['imgheight']="90";
$z[0][4]['imgwidth']="120";
$z[0][4]['infolen']="160";
$z[0][4]['titlelen']="60";
$z[0][4]['col']="1";
$z[0][4]['idlist']="";
$z[0][4]['name']="卡通动漫";
$z[0][4]['noteid']="1";
$z[0][4]['isauto']="0";
$z[0][4]['rownum']="40";
$z[0][4]['keywords']="";
$z[0][4]['typeid']="0";

?>