<?php
$z[0]=Array("global","",236,264);
$z[0][4]['name']="cfg_soft_lang";
$z[1]=Array("field","",277,296);
$z[1][4]['name']="title";
$z[2]=Array("global","",297,323);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("field","",364,386);
$z[3][4]['name']="keywords";
$z[4]=Array("field","",426,477);
$z[4][4]['name']="description";
$z[4][4]['function']="html2text(@me)";
$z[5]=Array("include","",826,863);
$z[5][4]['filename']="header.htm";
$z[6]=Array("global","",1001,1034);
$z[6][4]['name']="cfg_cmsurl";
$z[7]=Array("global","",1036,1070);
$z[7][4]['name']="cfg_webname";
$z[8]=Array("field","",1080,1099);
$z[8][4]['name']="title";
$z[9]=Array("field","",1146,1164);
$z[9][4]['name']="note";
$z[10]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\" title=\"[filed:fulltitle/][field:shorttitle/]\" target=\"_blank\">[field:title/][field:shorttitle/]</a></li>\r\n          ",1310,1534);
$z[10][4]['orderby']="click";
$z[10][4]['row']="14";
$z[10][4]['titlelen']="32";
$z[11]=Array("arclist","\r\n          <li><a href=\"[field:arcurl/]\" title=\"[filed:fulltitle/][field:shorttitle/]\" target=\"_blank\">[field:title/][field:shorttitle/]</a></li>\r\n          ",1792,2015);
$z[11][4]['orderby']="rand";
$z[11][4]['row']="14";
$z[11][4]['titlelen']="32";
$z[12]=Array("include","",2076,2113);
$z[12][4]['filename']="footer.htm";

?>